name: CI

# Updated workflow with improved server health checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Start Python Server
      run: |
        cd python-server
        pip install -r requirements.txt
        # Explicitly install uvicorn to ensure it's available
        pip install uvicorn
        # Start server with redirection of output to a log file for debugging
        nohup python run.py > server.log 2>&1 &
        echo $! > server.pid  # Save PID for potential troubleshooting
        # Wait for server to be properly initialized
        sleep 15  # Increased wait time
        # Verify server is running with curl health check
        MAX_RETRIES=5
        RETRY_COUNT=0
        until curl -s http://localhost:8000/health || [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
          echo "Waiting for server to be available... ($(($RETRY_COUNT+1))/$MAX_RETRIES)"
          RETRY_COUNT=$((RETRY_COUNT+1))
          sleep 5
        done
        
        if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
          echo "Server failed to start properly. Here are the logs:"
          cat server.log
          exit 1
        fi
        
        echo "Server successfully started!"
    
    - name: Test Python Server
      run: |
        cd python-server
        pytest
    
    - name: Test Java Client
      run: |
        cd java-client
        mvn test