name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    
    # Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r python-server/requirements.txt
        pip install pytest httpx
    
    # Create uploads directory (needed for tests)
    - name: Create uploads directory
      run: |
        mkdir -p python-server/uploads
        chmod 777 python-server/uploads
    
    # Run Java tests
    - name: Build and test Java client
      run: cd java-client && mvn test
    
    # Run Python tests
    - name: Test Python server
      run: |
        source venv/bin/activate
        cd python-server && python -m pytest tests/