name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Start Python Server
      run: |
        cd python-server
        pip install -r requirements.txt
        nohup python app.py &  # Assumes app.py is the entry point; adjust as necessary
        sleep 10  # Give the server some time to start
    
    - name: Test Python Server
      run: |
        cd python-server
        pytest
    
    - name: Test Java Client
      run: |
        cd java-client
        mvn test